<?php
if (!defined("PJ_HOST")) define("PJ_HOST", "localhost");
if (!defined("PJ_USER")) define("PJ_USER", "shopAdminPanel");
if (!defined("PJ_PASS")) define("PJ_PASS", "%3xp0rTech%");
if (!defined("PJ_DB")) define("PJ_DB", "shopExportech");
if (!defined("PJ_PREFIX")) define("PJ_PREFIX", "");
if (!defined("PJ_INSTALL_FOLDER")) define("PJ_INSTALL_FOLDER", "/admin/");
if (!defined("PJ_INSTALL_PATH")) define("PJ_INSTALL_PATH", "/home/exportechadmin/public_html/admin/");
if (!defined("PJ_INSTALL_URL")) define("PJ_INSTALL_URL", "https://www.exportechsolution.com/admin/");
if (!defined("PJ_SALT")) define("PJ_SALT", "FT9D07UL");
if (!defined("PJ_INSTALLATION")) define("PJ_INSTALLATION", "MjYxNTcxMDQxNjgzODQ2NDAzMzg4NTQxNjUxMjAxMzMyMzc3MzgwNDI1MDk2MjA0MDg0MDUwMDgzOTg2NjYzMzM4NzA1MDQ2NDUwMzYxMTIyNzM5NTk1NTQ3NjU5Njk4ODI1IDkyMjY4NTI4MTE2Mjc2MTIwNjk3Nzg4NzI4OTg2ODk0MTM3OTI5ODM5ODYyMjczODMyNDUzMTk0Njc5MTQ3Njg3NzQ5MTQ0MDE4Mzg0MTE5NDI3MjI3MjM1OTc3MjQ4MTQ2IDc2MTk1MjExMTQzMTYyODI1NTgxNTUyMzMyODY3MzY0MDc0NTg3MDM0OTY2MzgyMjcwMjI5NjYxNzQ2MTcxOTU3MDQzNTgwMDA4NDkxODk5NzE0MDcxNjk4NjgxOTY2OTg5OSAyMzg2NzQxNDA4MjkwNTk0MDUzOTc2MTQ0ODQwMzQzNjI1Njg0MTU4MzkwNDI2NDIzNDUwMDU1MjcxNDY1MzMyNDAxMDYwNjkxMjQ1MDQxMDU0MTg4ODU3Nzg4NjM4NzkyMDUgMTAwMDU0NTMxMDU5NTU4OTc0NTEyODU5NjkwMzkzODYwODYyNTk0NTQ4MDcxNDEyNzQ0MTkzMDIyNTU5NDM0MjIyNDMwNjU3ODA4NTE1MzEzMzMzODY1Mzk3NTU1OTIzMzk3NSAxMjYyNzk2MDkxNzM1MTMyMzUzNTI3ODA3OTUyNjYzNDA2NzcyODg0NDE4MDYzNjY4MjUwMTgwMzYwNjIxNTM4NTA5NzMyMDYwNjUyODk4NjM0NTIxNzI0MjM4ODIwMjI1MTY0IDE2MzUyMzczODkwMTc5MTU2MzkxNzE4MDY1ODQ1NDUyNTA5MjY4NTU2NDk3MjIyODQ5Nzk5NDMyNDgxODAzODQyODY2NjI5NDk4OTQwNjczNDI3NzIzNTYwMzE4Njg0MTEzMA==");
?>